# GitHub Repository Settings for Noru64 Split Keyboard

# Repository name: noru64-split-keyboard
# Description: ZMK firmware configuration for Noru64 split keyboard with center/peripheral architecture
# Topics: zmk, keyboard, split-keyboard, firmware, bluetooth, rgb, custom-keyboard

# Branch protection rules
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "build (noru64_split_center)"
          - "build (noru64_split_peripheral)"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false

# Issue templates
issue_templates:
  - name: Bug Report
    about: Report a bug in the firmware
    title: "[BUG] "
    body: |
      **Describe the bug**
      A clear and concise description of what the bug is.
      
      **To Reproduce**
      Steps to reproduce the behavior:
      1. Flash firmware to '...'
      2. Connect keyboard to '...'
      3. Press key '...'
      4. See error
      
      **Expected behavior**
      A clear and concise description of what you expected to happen.
      
      **Environment**
      - OS: [e.g. Windows 10, macOS 12, Ubuntu 20.04]
      - ZMK Version: [e.g. v3.0.0]
      - Board: [e.g. noru64_split_center, noru64_split_peripheral]
      
      **Additional context**
      Add any other context about the problem here.

  - name: Feature Request
    about: Suggest an idea for this project
    title: "[FEATURE] "
    body: |
      **Is your feature request related to a problem? Please describe.**
      A clear and concise description of what the problem is.
      
      **Describe the solution you'd like**
      A clear and concise description of what you want to happen.
      
      **Describe alternatives you've considered**
      A clear and concise description of any alternative solutions or features you've considered.
      
      **Additional context**
      Add any other context about the feature request here.

# Pull request template
pull_request_template: |
  ## Description
  Brief description of the changes made.
  
  ## Type of Change
  - [ ] Bug fix
  - [ ] New feature
  - [ ] Breaking change
  - [ ] Documentation update
  
  ## Testing
  - [ ] Tested on noru64_split_center
  - [ ] Tested on noru64_split_peripheral
  - [ ] Tested BLE connection
  - [ ] Tested USB connection
  
  ## Checklist
  - [ ] My code follows the project's style guidelines
  - [ ] I have performed a self-review of my own code
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings
