# This file generates the GitHub Actions matrix for Noru64 Split Keyboard
# 
# Boards:
# - noru64_split_center: Left side (Center) - USB connected, handles all input
# - noru64_split_peripheral: Right side (Peripheral) - BLE connected to center
#
# Build matrix will create separate jobs for each board
---

include:
  - board: noru64_split_center
    name: "Center (Left Side)"
    description: "USB connected, handles all keyboard input"
  - board: noru64_split_peripheral  
    name: "Peripheral (Right Side)"
    description: "BLE connected to center, sends input wirelessly"
  - board: nice_nano
    shield: settings_reset
    name: "Settings Reset"
    description: "Utility for resetting keyboard settings"
